/**
 * 基础档案 (cn.byteawake.ap.basedoc) — 行政区划类型枚举
 * Generated from ontology/byteawake-ap-basedoc.cn.byteawake.ap.basedoc.xml
 */

/** 行政区划类型 */
export const RegionType = {
  PROVINCE: 'PROVINCE',
  AUTONOMOUS_REGION: 'AUTONOMOUS_REGION',
  MUNICIPALITY: 'MUNICIPALITY',
  SAR: 'SAR',
  PREFECTURE_CITY: 'PREFECTURE_CITY',
  PREFECTURE: 'PREFECTURE',
  AUTONOMOUS_PREFECTURE: 'AUTONOMOUS_PREFECTURE',
  LEAGUE: 'LEAGUE',
  DISTRICT: 'DISTRICT',
  COUNTY: 'COUNTY',
  COUNTY_CITY: 'COUNTY_CITY',
  AUTONOMOUS_COUNTY: 'AUTONOMOUS_COUNTY',
  BANNER: 'BANNER',
  AUTONOMOUS_BANNER: 'AUTONOMOUS_BANNER',
  SPECIAL_DISTRICT: 'SPECIAL_DISTRICT',
  FORESTRY_AREA: 'FORESTRY_AREA',
  SUBDISTRICT: 'SUBDISTRICT',
  TOWN: 'TOWN',
  TOWNSHIP: 'TOWNSHIP',
  ETHNIC_TOWNSHIP: 'ETHNIC_TOWNSHIP',
  SUM: 'SUM',
  ETHNIC_SUM: 'ETHNIC_SUM',
  NEIGHBORHOOD_COMMITTEE: 'NEIGHBORHOOD_COMMITTEE',
  VILLAGE_COMMITTEE: 'VILLAGE_COMMITTEE',
  SIMILAR_VILLAGE_UNIT: 'SIMILAR_VILLAGE_UNIT',
} as const;
export type RegionType = (typeof RegionType)[keyof typeof RegionType];
